name = "BigCleaner"
uuid = "4f974a48-f082-421a-8589-c9cb9896bf90"
authors = ["Ronald Gamez"]
version = "0.1.0"

[deps]
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
PrettyTables = "1"
Tables = "1"
julia = "1.6"
